version: '3'
services:
  postgres-compose:
    image: postgres:latest
    environment:
      POSTGRES_DB: 'service'
      POSTGRES_PASSWORD: nicepass
      POSTGRES_USER: postgres
    ports:
      - "25432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    restart: always